//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiEtwTracing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SRResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SRResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiEtwTracing.SRResources", typeof(SRResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error from operation {0}.{1}: {2}.
        /// </summary>
        internal static string event_Error {
            get {
                return ResourceManager.GetString("event_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting operation {0}.{1}: {2}.
        /// </summary>
        internal static string event_OpBegin {
            get {
                return ResourceManager.GetString("event_OpBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed operation {0}.{1}: {2}.
        /// </summary>
        internal static string event_OpEnd {
            get {
                return ResourceManager.GetString("event_OpEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace of operation {0}.{1}: {2}.
        /// </summary>
        internal static string event_OpTrace {
            get {
                return ResourceManager.GetString("event_OpTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received {1} request {0}.
        /// </summary>
        internal static string event_Request {
            get {
                return ResourceManager.GetString("event_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending [{2} : {3}] response for {1} request {0}.
        /// </summary>
        internal static string event_Response {
            get {
                return ResourceManager.GetString("event_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning from operation {0}.{1}: {2}.
        /// </summary>
        internal static string event_Warning {
            get {
                return ResourceManager.GetString("event_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceptionMessage{0}=&apos;{1}&apos;.
        /// </summary>
        internal static string HttpErrorExceptionMessageFormat {
            get {
                return ResourceManager.GetString("HttpErrorExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceptionType{0}=&apos;{1}&apos;.
        /// </summary>
        internal static string HttpErrorExceptionTypeFormat {
            get {
                return ResourceManager.GetString("HttpErrorExceptionTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageDetail=&apos;{0}&apos;.
        /// </summary>
        internal static string HttpErrorMessageDetailFormat {
            get {
                return ResourceManager.GetString("HttpErrorMessageDetailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelStateError=[{0}].
        /// </summary>
        internal static string HttpErrorModelStateErrorFormat {
            get {
                return ResourceManager.GetString("HttpErrorModelStateErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}=[{1}].
        /// </summary>
        internal static string HttpErrorModelStatePairFormat {
            get {
                return ResourceManager.GetString("HttpErrorModelStatePairFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackTrace{0}={1}.
        /// </summary>
        internal static string HttpErrorStackTraceFormat {
            get {
                return ResourceManager.GetString("HttpErrorStackTraceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserMessage=&apos;{0}&apos;.
        /// </summary>
        internal static string HttpErrorUserMessageFormat {
            get {
                return ResourceManager.GetString("HttpErrorUserMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string task_Error {
            get {
                return ResourceManager.GetString("task_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpBegin.
        /// </summary>
        internal static string task_OpBegin {
            get {
                return ResourceManager.GetString("task_OpBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpEnd.
        /// </summary>
        internal static string task_OpEnd {
            get {
                return ResourceManager.GetString("task_OpEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpTrace.
        /// </summary>
        internal static string task_OpTrace {
            get {
                return ResourceManager.GetString("task_OpTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string task_Request {
            get {
                return ResourceManager.GetString("task_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string task_Response {
            get {
                return ResourceManager.GetString("task_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string task_Warning {
            get {
                return ResourceManager.GetString("task_Warning", resourceCulture);
            }
        }
    }
}
